name: Deploy to NixOS Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Build Angular app
        run: |
          nix-shell default.nix --run "npm install"
          nix-shell default.nix --run "npm run build"
      
      - name: Deploy to NixOS Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: "admin"
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          source: "build/*"
          target: "/home/admin/oxrinz-website"
          strip_components: 2