name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build SvelteKit app
        run: |
          npm install
          npm run build
      
      - name: Deploy to main
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: "admin"
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          source: "build/*"
          target: "/home/admin/oxrinz-website"
          strip_components: 1
          
      - name: Deploy backend to main
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: "admin"
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          source: "backend/*"
          target: "/home/admin/oxrinz-backend/backend"

      - name: Create env file with API key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: "admin"
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          script: |
            echo "WAKATIME_KEY=${{ secrets.WAKATIME_KEY }}" > /home/admin/oxrinz-backend/backend/.env
            chmod 600 /home/admin/oxrinz-backend/backend/.env